apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: network-resources-injector-pdb
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: network-resources-injector 
