apiVersion: v1
kind: Service
metadata:
  name: network-resources-injector-service
  namespace: kube-system
spec:
  ports:
  - port: 443
    targetPort: webhook
    name: webhook
  - port: 8444
    targetPort: health-check
    name: health-check
  selector:
    app: network-resources-injector
