FROM openshift/origin-release:golang-1.10 as builder
COPY . /usr/src/network-resources-injector
WORKDIR /usr/src/network-resources-injector
RUN make

FROM openshift/origin-base
COPY --from=builder /usr/src/network-resources-injector/bin/webhook /usr/bin/
COPY --from=builder /usr/src/network-resources-injector/bin/installer /usr/bin/

LABEL io.k8s.display-name="SRIOV Admission Controller"

CMD ["webhook"]
