FROM openshift/origin-release:golang-1.10 as builder

ENV PKG_NAME=github.com/intel/network-resources-injector
ENV PKG_PATH=$GOPATH/src/$PKG_NAME
WORKDIR $PKG_PATH

COPY . $PKG_PATH/
RUN go install ./cmd/...

FROM openshift/origin-base
COPY --from=builder /go/bin/webhook /go/bin/installer /usr/bin/

LABEL io.k8s.display-name="SRIOV Admission Controller"

CMD ["webhook"]
